### ISSUE TITLE
full projects?

### ISSUE THREAD

**Issue by goertzenator** [Sir4ur0n/blog#10]
Not being particularly skilled with `stack` I'm left a little confused about exactly where some of those edits are supposed to go.  Could you include those files too or perhaps just whole buildable projects?

**Comment by goertzenator** [comment]
Never mind, I didn't realize I was linked to a subdir.

**Comment by sir4ur0n** [comment]
Do you think there's anything I should change in the posts to make this more explicit?

**Comment by goertzenator** [comment]
Maybe just change the code link to https://github.com/Sir4ur0n/blog/tree/master/code-examples ?

**Comment by goertzenator** [comment]
Anyway, thank you for this series of blogs.  It has me started on polysemy and I am very excited!  Our code was just on the verge of getting tricky to manage with monad transformers and polysemy should clean that up nicely.

**Comment by sir4ur0n** [comment]
Actually I intentionally linked in each post to the sub-module dedicated to examples related to the post.

Maybe I should add a README in each sub-folder explaining it's a full Stack project...

Thank you for your feedback! It's much appreciated 😄
