### ISSUE TITLE
Polysemy notes

### ISSUE THREAD

**Issue by isovector** [Sir4ur0n/blog#6]
I just went through your tutorial, and it's excellent! Thanks for writing this. It's amazingly better than whatever crap I put in the readme when I first wrote it!

I had a few notes going through your tutorial. Nothing dramatic, but a few things to point out:

----

```
- -flate-specialise
- -fspecialise-aggressively
```

These are not necessary, and probably shouldn't be enabled unless you really know what you're doing. Definitely unnecessary for a beginner's tutorial!

---

```
> :t logInfo
```

Yeah, this is unfortunate. However, using `:info logInfo` instead will tell you `Member LogInfo r => String -> Sem r ()`!

---

Thanks again for the great post!

**Comment by sir4ur0n** [comment]
Thank you for your feedback! I just fixed the issues you mentioned, cheers
